### ISSUE TITLE
Renomear DAGS kernel_gate e kernel_changes 

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac-airflow#107]
### Descrição da tarefa

Os nomes *kernel_gate* e *kernel_changes* não comunicam, mesmo que minimamente, as responsabilidades das DAGs respectivas. 

Minha sugestão é que *kernel_gate* seja renomeada para *sync_isis_to_kernel*, e *kernel_changes* para *sync_kernel_to_website*.

## Considerações e notas

Caso a sugestão seja aceita, seria oportuna a implementação antes de termos uma instância em operação haja vista que pode causar efeitos operacionais na instância do Airflow.

**Comment by joffilyfe** [comment]
Na minha percepção essa mudança é benéfica, quanto aos nomes eu não tenho sugestões melhores.

**Comment by gustavofonseca** [comment]
Qual a opinião de vcs @jamilatta, @robertatakenaka e @patymori?

**Comment by jamilatta** [comment]
@gustavofonseca @joffilyfe 

Eu concordo com as alterações de nomes sugeridas pelo @gustavofonseca.
