### ISSUE TITLE
Adicionar o arquivo de dependência do Python

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac-airflow#112]
Para realizarmos a instalação sem o uso de **Docker** é necessário o arquivo com as dependências do **Python**, portanto, devemos criar um arquivo de **requirements.txt**

**Comment by jamilatta** [comment]
Item realizado no PR: https://github.com/scieloorg/opac-airflow/pull/113

**Comment by gustavofonseca** [comment]
> Item realizado no PR: #113

Este ticket pode ser fechado?

**Comment by jamilatta** [comment]
Sim!
