### ISSUE TITLE
Registrar URL legada para PDFs no banco do website

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/opac-airflow#115]
### Descrição da tarefa

Atualmente o website atende as URLs legadas por meio do código https://github.com/scieloorg/opac/blob/master/opac/webapp/controllers.py#L978-L979, os arquivos registrados no `object storage` não possuem os nomes originais e URLs originais ex `/aem/v60n2/0004-2730-aem-60-2-0143.pdf`.

Durante o cadastro dos `renditions` na base de dados do website é necessário registrar a URL legada para os PDFs do documento. As URLs dos `pdfs` que são atendidas pelo site antigo podem ser encontradas no link http://www.scielo.br/static_pdf_files.txt.

Exemplo de URL que precisará ser atendida: https://scielosp.org/pdf/rsp/v53/pt_0034-8910-rsp-53-03.pdf

### Subtarefas

- [x] Alterar DAG de registro de renditions para guardar o nome original do arquivo
- [x] Registrar URL legada na base do website

## Considerações e notas
N/A

**Comment by patymori** [comment]
Verificar o que foi feito no DS Migração:
scieloorg/document-store-migracao/pull/190
