### ISSUE TITLE
DAG sync_documents_to_kernel  registra documentos sem o scielo-id

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/opac-airflow#120]
### Descrição do problema

A DAG `sync_documents_to_kernel ` está registrando documentos que não possuem o `scielo-id` no XML.

### Passos para reproduzir o problema
1. Realize o processamento de sincronização de documentos com o pacote [1]
2. Verifique a lista de mudanças do Kernel
3. Localize a mudança de id `None`

### Comportamento esperado
A task de `register_update_docs_id` não deveria cadastrar documentos sem o `scielo-id`.

### Screenshots ou vídeos
N/A

### Anexos
[[1] - 7665_ag_2019nahead.zip](https://github.com/scieloorg/opac-airflow/files/3814626/7665_ag_2019nahead.zip)

### Ambiente utilizado

N/A

**Comment by jamilatta** [comment]
Adicionar uma msg nos logs informando os arquivo que não foram registrado por ausência de **scielo-id**

**Comment by jamilatta** [comment]
Nessa atividade é necessário uma instância do **Minio**, segue o comando para iniciar uma instância: 

``docker run -p 9000:9000 -e "MINIO_ACCESS_KEY=minio" -e "MINIO_SECRET_KEY=minio123" --name minio minio/minio server ~/minio/data``
