### ISSUE TITLE
Sincronização de pacotes Ahead of Print no fluxo de ingestão direta

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac-airflow#122]
### Descrição da nova funcionalidade
Eu, como **administrador do conteúdo do site novo**, gostaria que **os pacotes de Ahead of Print sejam sincronizados**, então **os documentos Ahead of Print que entrarem no fluxo direto de ingestão do SPF sejam publicados corretamente no novo site**.

### Critérios de aceitação
* Os documentos Ahead of Print deverão ser exibidos corretamente no site novo.
* Os documentos Ahead of Print deverão ser inseridos/alterados corretamente no kernel.
* Os documentos Ahead of Print deverão ser linkados ao maço de ahead of prints do periódico que, caso não exista, deve ser criado

### Anexos
N/A

### Referências
N/A

**Comment by jamilatta** [comment]
Pessoal irei dividir essa atividade em duas: 

1. Uma atividade que obtém esse dado no momento da execução da DAG para sincronização dos documentos com o Kernel. 
2. Uma atividade que obtém esse dado do Kernel na DAG de sincronização dos documentos no Site.
