### ISSUE TITLE
Sincronização de pacotes Ahead of Print no fluxo de documentos no Site.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac-airflow#124]
### Descrição da nova funcionalidade

Eu, como administrador do conteúdo do site novo, gostaria que os pacotes de **Ahead of Print** sejam sincronizados a partir do Kernel no novo site.

### Critérios de aceitação

- Os documentos **Ahead of Print** deverão ser exibidos corretamente no site novo.

### Anexos
N/A

### Referências
N/A

**Comment by jamilatta** [comment]
Para a realização dessa atividade, decidir explorar um pouco mais como realiza-lá, segue: 

Realizei alguns esperimentos com a API do Kernel para entender melhor como estava implementada o contexto do Ahead Of Print, para isso criei uma base de dados vazia do Kernel e executei os seguintes comandos com objetivo de visualizar o formato dos dados no Kernel, segue a sequência de comandos utilizados, para se ter o minímo para essa atividade: 

### Comando curl para criar um _periódico_ no Kernel: 

```shell
curl -X PUT -H 'Accept: application/json' -H 'Content-Type: application/json' http://0.0.0.0:6543/journals/0066-782XX -d '{"title": "Exemplo de journal"}'
```
### Comando curl para criar um _bundle_ no Kernel: 

```shell 
curl -X PUT -H 'Accept: application/json' -H 'Content-Type: application/json' http://0.0.0.0:6543/bundles/0066-782X-1999-v72-n0 -d '{"titles": [{"language": "pt", "value": "Bundle exemplo"}], "volume": "v1"}'
```
### Comando curl para criar um relacionamento de um bundle com um periódico no Kernel: 

```shell
curl -X PUT -H 'Accept: application/json' -H 'Content-Type: application/json' http://0.0.0.0:6543/journals/0066-782XX/issues -d '[{"id": "0066-782X-1999-v72-n0", "year": "2019"}]'
```
### Comando curl para criar um relacionamento de alguns documentos com um bundle no Kernel: 

```shell 
curl -X PUT -H 'Accept: application/json' -H 'Content-Type: application/json' http://0.0.0.0:6543/bundles/0066-782X-1999-v72-n0/documents -d '[{"id": "0034-8910-rsp-48-2-0347", "order": "01"}, {"id": "0034-8910-rsp-48-2-0348", "order": "02"}]' -v
```

### Comando curl para criar um relacionamento de um bundle como aop

```shell
curl -X PATCH -H 'Accept: application/json' -H 'Content-Type: application/json' http://0.0.0.0:6543/journals/0066-782XX/aop -d '{"aop": "0066-782X-1999-v72-n0"}' -v 
```

### Verificando os relacionamento no endpoint do journal

```shell
curl -X GET -H 'Accept: application/json' -H 'Content-Type: application/json' http://0.0.0.0:6543/journals/0066-782XX 
```

Formato do aop(Ahead Of Print) no endpoint de journal: 

![Screen Shot 2019-11-13 at 13 59 18](https://user-images.githubusercontent.com/373745/68788773-d1660400-0622-11ea-96c0-71823b5bf36a.png)

Reparem que temos somente um Ahead Of Print.

Passos para realizar essa atividade: 

1. Para a realização dessa atividade é necessário obter o valor do campo no endpoint do journal: http://0.0.0.0:6543/journals/0066-782XX (exemplo)
2. Com o **Id** do **bundle** aop é necessário cadastra um fascículo no **opac_schema** com o atributo _type="ahead"_ 
3. Adicionar os documentos e relacionar com o recém fascículo criado

**Comment by jamilatta** [comment]
@joffilyfe @robertatakenaka @patymori @gustavofonseca 

Alguma sugestão sobre o desenvolvimento dessa tarefa!

**Comment by gustavofonseca** [comment]
@jamilatta, não estou por dentro da modelagem de dados do Novo Site, mas não consigo enxergar uma grande variedade de soluções razoáveis. Trata-se de ler os dados de um serviço e cadastrar num banco de dados, e me parece que os 3 passos que vc sugeriu resolvem isso conforme esperado.

**Comment by jamilatta** [comment]
@gustavofonseca 

Ok.

**Comment by jamilatta** [comment]
Mais alguém tem alguma sugestão, opnião ou dúvida?

**Comment by joffilyfe** [comment]
No momento eu não consigo visualizar fluxos alternativos.
