### ISSUE TITLE
Incluir o PID da "versão 1".

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac-airflow#137]
### Descrição da tarefa

No tíquete https://github.com/scieloorg/PC-Programs/pull/3147 realizamos a adição dos PIDs na versão **2** e **3** no XML para SciELO Publishing Framework, porém a versão **1** não foi contemplada, já que estamos no contexto de artigos mais recentes. 

Nos documentos mais antigo que utilizavam a versão do **PID 1**, é necessário adicionar essa versão nos XML gerados pela migração.

## Considerações e notas

* A implementação dessa atividade resulta na resolução dos artigos na versão de PID 1 para o site novo e armazenamento desse dado na base de dados.

**Comment by joffilyfe** [comment]
Com base na discussão da issue #138 ficou acertado que o `airflow` será o responsável por popular um campo contendo todos os `pids` e suas versões no banco de dados do `Website`, por isso esta issue é considerada como duplicada.
