### ISSUE TITLE
PID não é armazenado no banco de dados do site.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac-airflow#138]
### Descrição do problema

Após realizarmos um processamento completo na nossa máquina de laboratório, identificamos que é armazenado O PID no banco de dados do site.

### Passos para reproduzir o problema

Acessando a base de dados do laboratório é possível visualizar essa ausência.

### Comportamento esperado

Para algumas views do site é necessário o PID e também para retro compatibilidade.

### Screenshots ou vídeos

<img width="1241" alt="Screenshot 2019-10-23 14 43 21" src="https://user-images.githubusercontent.com/373745/67420239-a0a32980-f5a4-11e9-996e-6e15d2bd9b5b.png">

### Ambiente utilizado

http://dsteste.scielo.br

**Comment by robertatakenaka** [comment]
- [ ] 1. criar no kernel as versões (v1, v2, v3) - resolve com https://github.com/scieloorg/clea/issues/4
- [ ] 2. criar no opac_schema também as 3 versões - este issue mesmo
- [ ] 3. sincronizar os dados das versões de PID do kernel para o opac - este issue mesmo
- [ ] 4. preparar o site novo para entender a URL da versão 1 - https://github.com/scieloorg/opac/issues/1485
