### ISSUE TITLE
Armazenar PID de issue durante espelhamento da base ISIS

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/opac-airflow#142]
### Descrição da tarefa

A fim de manter a compatibilidade de entre o site clássico e o site atual é necessário que o PID da issue seja capturado e salvo no `Kernel`.

Exemplo de [TOC](http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=0102-672020190001&lng=en&nrm=iso) que funciona no site clássico e que não funciona no [ambiente de testes](http://dsteste.scielo.br/scielo.php?script=sci_issuetoc&pid=0102-672020190001&lng=en&nrm=iso).

### Subtarefas

- [x] Ler da base ISIS o PID do issue e registrar no Kernel

## Considerações e notas
N/A

**Comment by jamilatta** [comment]
@joffilyfe 

Não sei se é necessário termos as páginas dos fascículos do site atual resolviveis no site novo! 

Em fase de desenvolvimento do OPAC decidimos que ireiamos manter a compatibilidade com as URL dos artigos!

**Comment by joffilyfe** [comment]
> @joffilyfe
> 
> Não sei se é necessário termos as páginas dos fascículos do site atual resolviveis no site novo!
> 
> Em fase de desenvolvimento do OPAC decidimos que ireiamos manter a compatibilidade com as URL dos artigos!

Hoje o ambiente de produção do novo site atende a URLs legadas de fascículos @jamilatta (ex [aqui](http://new.scielo.br/scielo.php?script=sci_issuetoc&pid=0102-672020190001&lng=en&nrm=iso), código [aqui](https://github.com/scieloorg/opac/blob/dae91e01909e3f6f14df59ff62dacbbd50211176/opac/webapp/main/views.py#L347)). Acredito que é importante manter essas páginas disponíveis, elas estão indexadas no google, podem estar referenciadas em vários contextos, por fim o esforço para faze-las funcionar nesta migração é mínimo.

**Comment by patymori** [comment]
Houve a necessidade de executar o espelhamento das bases ISIS com dados ainda não processados para o site, para obter dados mais atuais contendo os pacotes mais novos. Esbarramos no fato da base `issue` não possuir ainda o campo `v880` nos dados dos fascículos, o que causou um erro ao tentar obter o `Issue.publisher_id` através do Xylose para o payload do Kernel.
Concluímos que, neste caso, o ideal não seria utilizar o Xylose para obter um dado colocado no processamento do site atual e que pode não estar presente, mas que a aplicação, por conseguir montar o PID com os dados sempre presentes na base `issue`, pode formar o campo PID do fascículo e atualizar o Kernel. Assim também evitamos que outras aplicações que utilizam o Xylose sejam afetadas com uma alteração no comportamento da propriedade que captura o dado.

**Comment by joffilyfe** [comment]
> [..] mas que a aplicação, por conseguir montar o PID com os dados sempre presentes na base `issue`, pode formar o campo PID do fascículo e atualizar o Kernel [..]

@patymori você sabe qual é a estratégia utilizada para montar o PID?

**Comment by robertatakenaka** [comment]
A formação do PID de issue é:

```python
v35 + v36[0:4] + v36[4:].zfill(4)
```

**Comment by joffilyfe** [comment]
> A formação do PID de issue é:
> 
> ```python
> v35 + v36[0:4] + v36[4:].zfill(4)
> ```

Fantástico, @robertatakenaka.
