### ISSUE TITLE
[kernel2website] Artigos diferentes com segmento de URL iguais

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac-airflow#161]
### Descrição do problema
Há artigos sincronizados do Kernel para o site novo com o mesmo segmento de URL. Exemplos no fascículo http://dsteste.scielo.br/toc/aabc/2000.v72n4/:

* *Geochemical studies of the amazonian basin using transition elements and ree*
* *Discovering information through virtual reality*

Um dado que diferencia os dados dos documentos é a sequência do fpage.

### Passos para reproduzir o problema
1. Acesse http://dsteste.scielo.br/toc/aabc/2000.v72n4/
2. Clique no link do texto do artigo *Geochemical studies of the amazonian basin using transition elements and ree*
3. Observe o artigo acessado
4. Clique no link do texto do artigo *Discovering information through virtual reality*
5. Observe o artigo é o mesmo que o anterior

### Comportamento esperado
O segundo link acessado deveria acessar a página do artigo correta.

### Screenshots ou vídeos
N/A

### Anexos
.

### Ambiente utilizado
O problema foi identificado no ambiente dsteste.

### Observações
Esta correção depende da resolução do ticket https://github.com/scieloorg/articles_meta/issues/213.

**Comment by gustavofonseca** [comment]
O ticket https://github.com/scieloorg/articles_meta/issues/213 foi concluído e ao que tudo indica o problema observado não será resolvido com mudanças no código deste repositório, certo? É razoável fecharmos este ticket e abrirmos um _card_ de natureza operacional no quadro de atividades?

**Comment by patymori** [comment]
> O ticket [scieloorg/articles_meta#213](https://github.com/scieloorg/articles_meta/issues/213) foi concluído e ao que tudo indica o problema observado não será resolvido com mudanças no código deste repositório, certo? É razoável fecharmos este ticket e abrirmos um _card_ de natureza operacional no quadro de atividades?

@gustavofonseca, é necessário alterar a parte do código da sincronização pois o opac_schema não está sendo alimentado com o dado e, portanto, não sendo salvo na base do Opac.

**Comment by gustavofonseca** [comment]
Não seria este o código responsável? https://github.com/scieloorg/opac-airflow/blob/06ce676a74d863eb381a26ae21c7890a73c84673/airflow/dags/operations/sync_kernel_to_website_operations.py#L228

**Comment by patymori** [comment]
@gustavofonseca, tem razão. Estou encerrando este.
