### ISSUE TITLE
[FASE 3] Levantar/discutir alternativas para que o GeraPadrao.bat SPF não interfira no GeraScielo.bat

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac-airflow#206]
### Descrição da tarefa
Levantar alternativas para que o `GeraPadrao.bat` SPF não interfira no `GeraScielo.bat`

Quando executado dia 10/08, o `PreSyncToKernel.bat` que é executado dentro de `GeraPadrao.bat` em paralelo com `GeraScielo.bat`, pode ter ou não interferido no tempo de execução do `GeraScielo.bat`, aumentando em até 5h.

**NOTA**: apesar do atraso, acabou por volta das 8h, em teoria não impactaria na rotina da equipe

**Comment by robertatakenaka** [comment]
#### Proposta 1
Dia 12/08, infra sugeriu que no lugar de executar o `rsync`, fosse feito um `mv` local e, pós `GeraScielo.bat`, executasse o `rsync`

#### Proposta 2
- Voltar à versão original do GeraPadrao.bat para o processamento do dia 12/8
- Voltar a versão SPF no dia 14/8 e comparar o tempo dos processamentos do dia 12 e 14.

**Comment by patymori** [comment]
**Proposta 3**
Infra também sugeriu no dia 12/08 que, ao invés de executar o `rsync` da máquina `homolog-metodologia`, o Airflow moveria os arquivos, lendo do diretório local em `homolog-metodologia` para o storage.

**Comment by robertatakenaka** [comment]
**Proposta 4**
No script `PreSyncToKernel.bat`, no lugar de usar `rsync`, usar `mc`. Implicações:

Instalação do mc
```
# inclusão do host para ter acesso
./mc config host a <alias> <URL> <user> <pass>

# criação de uma pasta no destino
./mc mb <alias>/<destino>

# copia de um pacote
./mc cp <fonte> <alias>/<destino>
```

Ajustes no opac-airflow para ler do minIO, ao invés do volume

**Comment by robertatakenaka** [comment]
Estamos neste momento testando a **Proposta 3**, `/var/www/scielo_br/spf_htm`, pasta local, e do ponto de vista do airflow-hml.scielo.br será um ponto de montagem.

**Comment by jamilatta** [comment]
Assim como comentado pela Roberta: https://nfe.prefeitura.sp.gov.br/contribuinte/notaprint.aspx?ccm=54965578&nf=93&cod=S5DXWEXL alteramos para o que o **airflow-hml.scielo.br**  passe a olhar para os arquivos dos pacotes e da **scilista.lst** em uma pasta local de uma **máquina física**. 

Comprovamos em alguns teste que o tempo de cópia melhorou significativamente, consideramos esse problema resolvido.
