### ISSUE TITLE
Consultar pacotes não publicados pelo fluxo de ingestão direta no SPF

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac-airflow#212]
### Descrição da nova funcionalidade
Eu, como **desenvolvedor de software**, gostaria que **fosse possível consultar pacotes não publicados pelo fluxo de ingestão direta no SPF**, então **seria possível saber quais pacotes não foram publicados pelo fluxo de ingestão direta por não ter o pacote convertido ao final da execução da nova versão do XC**.

### Critérios de aceitação
- Deve informar a data do processamento
- Deve informar o periódico e fascículo ao qual o pacote está relacionado
- Deve ser possível filtrar pela data, periódico e fascículo

### Anexos
.

### Referências
.

**Comment by jamilatta** [comment]
Em conversa com a equipe, verificamos que existe a possibilidade dessa atividade não ser realizada, é necessária uma conversa com a equipe para verificar! 

@scieloorg/scielo-ps-developers preciso de ajuda sobre esse tíquete.

**Comment by jamilatta** [comment]
Em conversa com equipe sinto que devemos avaliar esse desenvolvimento em outro momento, portanto, estou fechando esse tíquete.
