### ISSUE TITLE
Definir identificação dos fascículos

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac-airflow#40]
Diante da necessidade do site ter a identificação do "tipo" de fascículo, precisamos discutir como o opac-airflow irá identificar essa tipagem dos fascículos para o opac_schema ou se iremos passar a tratar todos com o mesmo "tipo".

Atualmente o processamento obtém esses dados a partir do xylose que realiza essa identificação, veja: https://github.com/scieloorg/xylose/blob/3f365a25b20847da658f52bbf47e2204b8f3bd71/xylose/scielodocument.py#L261

**Comment by joffilyfe** [comment]
Foi definido que os identificadores dos fascículos serão formados por `issn-ano-volume-número-suplemento`.
