### ISSUE TITLE
Deleção de Fascículos pela Scilista

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac-airflow#56]
Implementar a deleção de Bundles (fascículos) do Kernel e os documentos relacionados a ele quando o comando DEL foi identificado na `scilista.lst`. Segue um exemplo de como o comando é representado no arquivo:

`abc 2015nahead del`

Este comando **não** deve excluir o conteúdo do Object Store

**Comment by patymori** [comment]
Quando o comando `del` for para um fascículo regular, contínuo ou não, é esperado que todos os documentos relacionados a ele sejam "apagados", sendo marcados como tal no Kernel.
Quando se tratar de um issue *Ahead of Print*, é esperado que somente os documentos relacionados a ele do ano indicado na scilista sejam marcados como excluídos do Kernel.

**Comment by robertatakenaka** [comment]
Quando vc diz "Este comando não deve excluir o conteúdo do Object Store" seriam os arquivos do minIO?

**Comment by patymori** [comment]
> Quando vc diz "Este comando não deve excluir o conteúdo do Object Store" seriam os arquivos do minIO?

Isso é necessário para manter as versões anteriores dos documentos e ativos digitais.

**Comment by robertatakenaka** [comment]
@scieloorg/scielo-brazil-developers temos que dar uma solução quando se deseja remover o fascículo + seus documentos porque ele realmente não deveria existir, por erro de registro. É raro mas pode acontecer de o editor mudar de idéia ou haver erro ao registrar. Aí tudo deveria ser removido sem deixar versões anteriores. Mas isso acho que é a parte do "scilista del"

**Comment by patymori** [comment]
> @scieloorg/scielo-brazil-developers temos que dar uma solução quando se deseja remover o fascículo + seus documentos porque ele realmente não deveria existir, por erro de registro. É raro mas pode acontecer de o editor mudar de idéia ou haver erro ao registrar. Aí tudo deveria ser removido sem deixar versões anteriores. Mas isso acho que é a parte do "scilista del"

Considero que isso seria um caso de exceção, diferente do que acontece com este comando, que acontece regularmente. Como é uma demanda fora do escopo deste issue, talvez seja necessário criar um outro para tratar dessa funcionalidade.

**Comment by robertatakenaka** [comment]
> seja necessário criar um outro para tratar dessa funcionalidade

minha dúvida é: onde criar

**Comment by joffilyfe** [comment]
> @scieloorg/scielo-brazil-developers temos que dar uma solução quando se deseja remover o fascículo + seus documentos porque ele realmente não deveria existir, por erro de registro. É raro mas pode acontecer de o editor mudar de idéia ou haver erro ao registrar. Aí tudo deveria ser removido sem deixar versões anteriores. Mas isso acho que é a parte do "scilista del"

Acho que essa necessidade foge até do escopo da nova plataforma. No meu entendimento nada deveria ser deletado fisicamente.

> minha dúvida é: onde criar

Provavelmente fora do Kernel.

**Comment by patymori** [comment]
> Acho que essa necessidade foge até do escopo da nova plataforma. No meu entendimento nada deveria ser deletado fisicamente.
Discordo por entender que a nova plataforma foi pensada para manter os conteúdos que devem ser publicados e estarem públicos. Já discutimos anteriormente que talvez seria o caso de criarmos uma funcionalidade para remover este conteúdo do Kernel e do Object Store, de conteúdos que não deveriam ter sido enviados para publicação e foram por erro, mediante a uma senha administrativa ou algo assim.
Não acho que é o momento de discutirmos este caso de uso agora, principalmente neste ticket, pois criaria confusão. Porém, é importante ter em mente que, se isso acontecer, por enquanto a remoção terá que ser manual.

**Comment by gustavofonseca** [comment]
> @scieloorg/scielo-brazil-developers temos que dar uma solução quando se deseja remover o fascículo + seus documentos porque ele realmente não deveria existir, por erro de registro. É raro mas pode acontecer de o editor mudar de idéia ou haver erro ao registrar. Aí tudo deveria ser removido sem deixar versões anteriores. Mas isso acho que é a parte do "scilista del"

Não há essa possibilidade, por design. Pela perspectiva do Kernel todo o conteúdo que uma vez existiu, existiu. Talvez a gente possa projetar outros mecanismos de controle de acesso de mais alto nível sobre o Kernel para garantir este caso de uso.

**Comment by joffilyfe** [comment]
> [...] Já discutimos anteriormente que talvez seria o caso de criarmos uma funcionalidade para remover este conteúdo do Kernel e do Object Store [..].

Não me recordo dessa discussão mas a deleção lógica resolve isso. Se pensarmos no `kernel` como uma estrutura imutável então deleções físicas quebram esse princípio. Até para uma eventual auditoria é interessante saber que aquele registro existiu.

> Não acho que é o momento de discutirmos este caso de uso agora [..]

Concordo.

**Comment by gustavofonseca** [comment]
> Não me recordo dessa discussão mas a deleção lógica resolve isso. Se pensarmos no `kernel` como uma estrutura imutável então deleções físicas quebram esse princípio. Até para uma eventual auditoria é interessante saber que aquele registro existiu.

Exatamente.

**Comment by patymori** [comment]
> Não me recordo dessa discussão mas a deleção lógica resolve isso. Se pensarmos no `kernel` como uma estrutura imutável então deleções físicas quebram esse princípio. Até para uma eventual auditoria é interessante saber que aquele registro existiu.
> 
Essa conversa foi há muito tempo atrás e, talvez, não faça mais sentido neste momento. Se acham que o conteúdo precisa permanecer no Kernel para sabermos que foi registrado errado, concordo que não devemos apagar. Contudo, se não é um problema a ser resolvido agora, não vamos nos preocupar em discutí-lo, principalmente neste ticket.

**Comment by patymori** [comment]
Fiquei com duas dúvidas enquanto pensava em uma proposta de solução:

- Se há comando `del` e registro/atualização para um mesmo fascículo na Scilista, a deleção precisa ocorrer com sucesso para que o registro/atualização dos pacotes seja feita?
- Se há uma sequencia de pacotes para um mesmo fascículo, caso algum dê falha, faz sentido sincronizar os demais?
