### ISSUE TITLE
Implementar estrutura para armazenamento de falhas e dados importantes dos processamentos

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/opac-airflow#77]
### Descrição da tarefa

É necessário implementar uma interface para armazenar os pontos de falha e suas causas nos processamentos orquestrados pelas dags de espelhamento e pré &sincronização de pacotes SPS.

Ao finalizar um processamento completo ou parcial devemos ser capazes de extrair informações como por exemplo:
- Quais Journals `não` foram espelhados 
- Quais Issues `não` foram espalhadas
- Quais Issues `não`foram relacionadas
- Quais documentos `não` foram inseridos/atualizados
  - Qual foi o motivo pelo qual o documento `não` pode ser inserido/atualizado
- Quais documentos `não` foram deletados
  - Qual foi o motivo pelo qual o documento `não` pode ser deletado
- Quantos documentos `não` puderam ser processados no processamento `X`
- Quantos documentos `não` puderam ser processados no processamento a partir da data `Y`
- Qual foi o último processamento a falhar
- Qual foi a `task` do processamento que falhou

Também faz-se necessário guardar dados importantes dos processamentos como:
- Quantidade de documentos processados com sucesso
- Documentos que foram processados com sucesso
- Lista de pacotes que foram processados com sucesso

### Subtarefas

- [ ] Determinar estruturas que armazenarão os dados
- [ ] Alterar dags para capturar os erros

## Considerações e notas
N/A

**Comment by joffilyfe** [comment]
É preciso analisar e especificar a forma de armazenamento destas informações. Alguma sugestão?

**Comment by patymori** [comment]
Item a ser adicionado na lista de informações:
* Documentos ex-ahead of prints publicados com sucesso em fascículo regular
