### ISSUE TITLE
[changes] Adequar relacionamento de periódicos e bundles às mudanças do Kernel

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac-airflow#79]
### Descrição da tarefa
Houve alteração nos dados dos __Documents Bundles__ no periódico. Agora, ao invés de somente uma lista de ID de bundles, o Kernel armazena uma lista de dicionários com a seguinte estrutura:

```
[
    {
        "id": <id do Bundle>,
        "ns": [<ano>, <volume>, <número>, <supplemento>],
    },
]
```
Obs: Pensar em outra estrutura.

**Comment by joffilyfe** [comment]
Durante a abertura desta `issue` a estrutura do `item` de relacionamento entre `Journal` e `Issue` foi discutida com o intuito de oferecer uma conveniência maior ao consumidor dos dados.

Antes de continuarmos com esta atividade é preciso entender em um contexto mais amplo as necessidades dos possíveis clientes destes dados e como estes dados serão utilizados, uma vez que a posição/agrupamento do item deve importar em contextos distintos.

A *grade de fascículos* do [OPAC](https://new.scielo.br) é um potencial cliente da estrutura de relacionamento. O `namespace` é capaz de informar em qual linha da matriz o item deve ser renderizado embora não seja possível determinar em qual coluna o item deve ser posicionado.

Foi levantada a possibilidade de utilizar uma estrutura menos rígida do que a adotada pelo `namespace`, exemplo:

```json
{
    "id": "bundle_id",
    "order": "0001",
    "number": "01",
    "volume": "02",
    "year": "2019",
    "supplement": "supplement"
}
```

A obrigatoriedade dos dados existirá apenas para os campos `id` e `order`.

Devemos aprofundar a discussão entre os prós e contras em alterar os dados do relacionamento, /summon @robertatakenaka @patymori @cesarbruschetta @jamilatta

**Comment by patymori** [comment]
Somente para complementar, esta proposta de estrutura tem o desafio de ser mantida atualizada, tendo em vista que, caso os dados do bundle correspondente ao id sejam alterados, os dados da estrutura também deveriam.

**Comment by robertatakenaka** [comment]
Concordo com esta estrutura:
```python
{
    "id": "bundle_id",
    "order": "0001",
    "number": "01",
    "volume": "02",
    "year": "2019",
    "supplement": "supplement"
}
```
Mas precisamos começar a usar a data mais completa possível, acrescentando os meses.
Já há um issue para lidar com isso: https://github.com/scieloorg/document-store/issues/170
