### ISSUE TITLE
[changes] Registrar fascículos com tipo diferente de "regular"

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac-airflow#93]
### Descrição da tarefa
Todos os fascículos que estão sendo registrados no OPAC estão com tipo `regular`. É necessário verificar a presença do campo `supplement` e, em caso afirmativo, o fascículo deve ser registrado com `"type": "supplement"`
Também verificar se o tipo é `volume_issue`, de publicação contínua.

**Comment by joffilyfe** [comment]
Atualmente o OPAC/Schema aceita os valores [1], esta `issue` deve resolver o cadastro dos tipos `volume_issue`, `supplement`, `special` e `regular`.

**[1] Valores aceitos pelo OPAC**

```python
{
    "ahead",
    "outdated_ahead",
    "pressrelease",
    "regular",
    "special",
    "supplement",
    "volume_issue"
}
```
